version: '3'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    hostname: redis
    volumes:
      - redis-data:/data/redis
    networks:
      - redis_network
    command: [ "redis-server"]
  app:
    container_name: app
    restart: always
    env_file: .env
    build: .
    expose:
      - "5005"
    depends_on:
      - db
      - nginx
    networks:
      - db_network
      - web_network
      - redis_network
  celery:
    container_name: celery
    build:
      context: .
      dockerfile: DockerfileCelery
    command: celery -A app.celery worker
    user: nobody
    depends_on:
      - redis
      - app
    env_file: .env
    restart: always
    networks:
      - web_network
      - redis_network
    
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
  db:
    image: "postgres"
    env_file: .env
    restart: always
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    networks:
      - db_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
  redis_network:
    driver: bridge
volumes:
  my_dbdata:
  redis-data: