"""empty message

Revision ID: 0d7c1a126270
Revises: bb598b183353
Create Date: 2020-07-21 00:41:43.021232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7c1a126270'
down_revision = 'bb598b183353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PortfolioMaster', sa.Column('losses', sa.REAL(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PortfolioMaster', 'losses')
    # ### end Alembic commands ###
