"""empty message

Revision ID: 1b612e4e2cd3
Revises: 9af21d09db6d
Create Date: 2020-07-15 03:01:02.462836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b612e4e2cd3'
down_revision = '9af21d09db6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DepositRequests', sa.Column('dateApproved', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DepositRequests', 'dateApproved')
    # ### end Alembic commands ###
