"""empty message

Revision ID: 29ced810bf4f
Revises: 648731ac1449
Create Date: 2020-07-21 01:12:58.259618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ced810bf4f'
down_revision = '648731ac1449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('DepositRequests', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('GainsAndLoss', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('PartnersGainsAndLoss', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('PortfolioMaster', 'weight',
               existing_type=sa.NUMERIC(),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PortfolioMaster', 'weight',
               existing_type=sa.REAL(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('PartnersGainsAndLoss', 'amount',
               existing_type=sa.Numeric(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('GainsAndLoss', 'amount',
               existing_type=sa.Numeric(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('DepositRequests', 'amount',
               existing_type=sa.Numeric(),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
