"""empty message

Revision ID: 41a7c8118320
Revises: 6da0904bf082
Create Date: 2020-07-23 18:49:10.664425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a7c8118320'
down_revision = '6da0904bf082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('CeleryHealth', 'taskID',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('CeleryHealth', 'taskID',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    # ### end Alembic commands ###
