"""empty message

Revision ID: 5be3bbb17286
Revises: 4b16efe88459
Create Date: 2020-07-17 18:33:29.341892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '5be3bbb17286'
down_revision = '4b16efe88459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PortfolioMaster', sa.Column('gains', sa.REAL(), nullable=True))
    op.add_column('PortfolioMaster', sa.Column('total', sa.REAL(), nullable=True))
    op.add_column('PortfolioMaster', sa.Column('withdrawls', sa.REAL(), nullable=True))
    op.alter_column('PortfolioMaster', 'invested', existing_type=sa.Integer(), type_=sa.REAL())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PortfolioMaster', 'withdrawls')
    op.drop_column('PortfolioMaster', 'total')
    op.drop_column('PortfolioMaster', 'gains')
    op.alter_column('PortfolioMaster', 'invested', type_=sa.REAL(), existing_type=sa.Integer())
    # ### end Alembic commands ###
