"""empty message

Revision ID: 6da0904bf082
Revises: 72f522873874
Create Date: 2020-07-23 18:35:03.801772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da0904bf082'
down_revision = '72f522873874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CeleryHealth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taskID', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CeleryHealth')
    # ### end Alembic commands ###
