"""empty message

Revision ID: 72f522873874
Revises: c31fc37a35ed
Create Date: 2020-07-22 22:23:00.432786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72f522873874'
down_revision = 'c31fc37a35ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TaxesandFees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxes', sa.Numeric(), nullable=True),
    sa.Column('fees', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WithdrawlRequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('fees', sa.Numeric(), nullable=True),
    sa.Column('taxes', sa.Numeric(), nullable=True),
    sa.Column('paidout', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('dateApproved', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WithdrawlRequests')
    op.drop_table('TaxesandFees')
    # ### end Alembic commands ###
