"""empty message

Revision ID: 98118f485a60
Revises: ef808551631c
Create Date: 2020-07-12 23:40:30.577263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98118f485a60'
down_revision = 'ef808551631c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PortfolioMaster', sa.Column('weight', sa.REAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PortfolioMaster', 'weight')
    # ### end Alembic commands ###
