"""empty message

Revision ID: 9af21d09db6d
Revises: e1f42733a480
Create Date: 2020-07-15 01:40:17.442736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9af21d09db6d'
down_revision = 'e1f42733a480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GainsAndLoss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.REAL(), nullable=True),
    sa.Column('gainType', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('PartnersGainsAndLoss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.REAL(), nullable=True),
    sa.Column('gainType', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PartnersGainsAndLoss')
    op.drop_table('GainsAndLoss')
    # ### end Alembic commands ###
