"""empty message

Revision ID: b6dd57b22713
Revises: 41a7c8118320
Create Date: 2020-07-23 18:50:17.293812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6dd57b22713'
down_revision = '41a7c8118320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('CeleryHealth', 'status',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('CeleryHealth', 'status',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    # ### end Alembic commands ###
