"""empty message

Revision ID: c31fc37a35ed
Revises: 29ced810bf4f
Create Date: 2020-07-21 01:24:02.432919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31fc37a35ed'
down_revision = '29ced810bf4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PartnersGainsAndLoss', 'calcWeight',
               existing_type=sa.REAL(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.add_column('PortfolioMaster', sa.Column('gltotal', sa.Numeric(), nullable=True))
    op.alter_column('PortfolioMaster', 'weight',
               existing_type=sa.REAL(),
               type_=sa.Numeric(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PortfolioMaster', 'weight',
               existing_type=sa.Numeric(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('PortfolioMaster', 'gltotal')
    op.alter_column('PartnersGainsAndLoss', 'calcWeight',
               existing_type=sa.Numeric(),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
