"""empty message

Revision ID: d28e51d247e5
Revises: 2f28f09b521f
Create Date: 2020-07-12 13:58:45.290575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28e51d247e5'
down_revision = '2f28f09b521f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DepositHistory', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('DepositRequests', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DepositRequests', 'date')
    op.drop_column('DepositHistory', 'date')
    # ### end Alembic commands ###
