"""empty message

Revision ID: e2c269bfbdd0
Revises: 5aa505f63d73
Create Date: 2020-07-11 17:34:25.935572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c269bfbdd0'
down_revision = '5aa505f63d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PortfolioMaster', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PortfolioMaster', 'name')
    # ### end Alembic commands ###
