"""empty message

Revision ID: ee90ed45fc44
Revises: 0d7c1a126270
Create Date: 2020-07-21 00:57:02.324442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee90ed45fc44'
down_revision = '0d7c1a126270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PortfolioMaster', 'gains',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('PortfolioMaster', 'losses',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('PortfolioMaster', 'total',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('PortfolioMaster', 'weight',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('PortfolioMaster', 'withdrawls',
               existing_type=sa.REAL(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PortfolioMaster', 'withdrawls',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('PortfolioMaster', 'weight',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('PortfolioMaster', 'total',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('PortfolioMaster', 'losses',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('PortfolioMaster', 'gains',
               existing_type=sa.REAL(),
               nullable=True)
    # ### end Alembic commands ###
