"""empty message

Revision ID: ef808551631c
Revises: d28e51d247e5
Create Date: 2020-07-12 15:06:09.584984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef808551631c'
down_revision = 'd28e51d247e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DepositRequests', sa.Column('status', sa.String(), nullable=True))
    op.add_column('DepositRequests', sa.Column('userID', sa.Integer(), nullable=True))
    op.drop_column('DepositRequests', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DepositRequests', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.drop_column('DepositRequests', 'userID')
    op.drop_column('DepositRequests', 'status')
    # ### end Alembic commands ###
